;[program:signal-telegram-worker-fa]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/signal-telegram/artisan queue:work database --queue=telegram-fa,default --sleep=3 --tries=3 --max-time=3600 --timeout=600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/signal-telegram/storage/logs/worker-fa.log
stopwaitsecs=3600

[program:signal-telegram-worker-en]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/signal-telegram/artisan queue:work database --queue=telegram-en,default --sleep=3 --tries=3 --max-time=3600 --timeout=600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/signal-telegram/storage/logs/worker-en.log
stopwaitsecs=3600
