;[program:signal-telegram-horizon]
command=php /var/www/signal-telegram/artisan horizon
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/signal-telegram/storage/logs/horizon.log
stopwaitsecs=3600
